# Generated by Django 3.0.3 on 2021-10-31 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=200)),
                ('imageField', models.CharField(max_length=400)),
                ('points', models.IntegerField()),
                ('nb_answer', models.IntegerField()),
                ('nb_image', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.Question')),
            ],
        ),
    ]
